blog/urls.py
from django.urls import path
from blog.views import *

urlpatterns = [
    path('', post_list, name='post_list'),
    path('post/draft', post_draft, name='post_draft'),
    path('post/category/<int:category_pk>', categories, name='categories'),
    path('post/detail/<int:post_pk>', post_detail, name='post_detail'),
    path('post/edit/<int:post_pk>', post_edit, name='post_edit'),
    path('post/published/<int:post_pk>', published_post, name='published_post'),
    path('post/delete/<int:post_pk>', post_delete, name='post_delete'),
    path('post/detail/comment_delete/<int:post_pk>/<int:comment_pk>', comment_delete,
         name='comment_delete'),
    path('post/new/', post_new, name='post_new'),
    path('post/detail/feedback/<int:post_pk>', feedback, name='feedback'),
    path('recommendations', recomends, name='recomends'),
    path('my_posts', my_posts, name='my_posts'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

blog/models.py
from django.db import models
from users.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Post(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE,
                                 blank=True, null=True)
    title = models.CharField(
        max_length=64, verbose_name='Title'
    )
    text = models.TextField(
        verbose_name='Text'
    )
    created_date = models.DateTimeField(
        verbose_name='Created Date', auto_now_add=True
    )
    publish_date = models.DateTimeField(
        verbose_name='Publish Date'
    )
    published = models.BooleanField(default=False)

    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        blank=True, null=True
    )
    def __str__(self):
        return f'{self.title}'

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField(
        verbose_name='Text')
    publish_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Publish Date')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.text}'

class Category(models.Model):
    text = models.CharField(max_length=64, verbose_name='Text')

    def __str__(self):
        return f'{self.text}'

class Feedback(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='feedbacks',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='Text'
    )
    date = models.DateTimeField(
        auto_now_add=True
    )
    rating = models.IntegerField(
        verbose_name='Rating',
        default=1
    )

    def __str__(self):
        return f'{self.text}'

blog/forms.py
from django import forms
from blog.models import Post, Comments, Feedback
from django.forms import ModelForm, Textarea

REVIEW_CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "text",
        )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('text',
        )
        widgets = {
            'text': Textarea(attrs={'rows': 4, 'cols': 40}),
        }

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('text', 'rating'
        )
        widgets = {
            'text': Textarea(attrs={'rows': 4, 'cols': 40}), 'rating': forms.RadioSelect(choices=REVIEW_CHOICES)
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Post, Comments, Category, Feedback
from blog.forms import PostForm, CommentForm, FeedbackForm
from datetime import datetime
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from users.models import User

def post_list(request):
    posts = Post.objects.all().filter(published=True)
    category = Category.objects.all()
    counter = posts.count()
    return render(request, 'blog/post_list.html', {'items': posts, 'category': category,
                                                   'counter': counter})
@login_required
def post_new(request):
    if request.method == "GET":
        form = PostForm()
        return render(request, 'blog/post_new.html', {'form': form})
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_date = datetime.now()
            post.publish_date = datetime.now()
            post.author = request.user
            post.save()
            return redirect('post_detail', post_pk=post.pk)


def categories(request, category_pk):
    posts = Post.objects.filter(category=category_pk)
    category = Category.objects.all()
    return render(request, 'blog/post_list.html', {'items': posts,
                                                   'category': category})
def recomends(request):
    posts = Post.objects.values('title', 'pk').annotate(Avg('feedbacks__rating')).order_by('-feedbacks__rating__avg')[:5]
    return render(request, 'blog/post_recomends.html', {'spisok': posts})

def post_draft(request):
    posts = Post.objects.all().filter(published=False)
    return render(request, 'blog/post_list.html', {'items': posts})


@login_required
def published_post(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.published = True
    post.save()
    return render(request, 'blog/post_detail.html', {'post': post})

def rating(post_pk):
    fb = Feedback.objects.filter(post=post_pk)
    count = sum([i.rating for i in fb]) / fb.count()
    return round(count, 1)

def post_detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comments = Comments.objects.all().filter(post=post_pk)
    counter = comments.count()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            user = request.user
            if user.is_authenticated:
                comment.author = request.user
            else:
                return redirect('/users/login/')
            comment.post = post
            comment.published_date = datetime.now()
            comment.save()
            return redirect('post_detail', post_pk=post.pk)
    else:
        comment_form = CommentForm()
    fb = Feedback.objects.filter(post=post_pk)
    counts = round(((sum([i.rating for i in fb])) / fb.count()), 1)
    return render(request, 'blog/post_detail.html', {'post': post,
                                                     'comments': comments,
                                                     'counter': counter,
                                                     'comment_form': comment_form,
                                                     'counts': counts})


@login_required
def post_edit(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    # post = Post.objects.filter(pk=post_pk)
    if request.method == "GET":
        form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form': form})
    else:
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_date = datetime.now()
            post.publish_date = datetime.now()
            post.save()
            return redirect('post_detail', post_pk=post.pk)

@login_required
def post_delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk).delete()
    return redirect('post_list')

@login_required
def comment_delete(request, post_pk, comment_pk):
    post = Post.objects.get(pk=post_pk)
    comment = get_object_or_404(Comments, pk=comment_pk).delete()
    return redirect('post_detail', post_pk=post.pk)


def feedback(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    fb = Feedback.objects.filter(post=post_pk)
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        if feedback_form.is_valid():
            feedback = feedback_form.save(commit=False)
            user = request.user
            if user.is_authenticated:
                feedback.author = request.user
            else:
                return redirect('/users/login/')
            feedback.post = post
            feedback.date = datetime.now()
            feedback.save()
            return redirect('feedback', post_pk=post.pk)
    else:
        feedback_form = FeedbackForm()
    context = {'fb': fb,
               'post': post,
               'feedback_form': feedback_form}
    return render(request, 'blog/feedback.html', context)

@login_required
def my_posts(request):
    post = Post.objects.filter(author=request.user)
    return render(request, 'blog/my_posts.html', {'items': post})

blog/templates/blog/feedback.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feedback</title>
    <link href="{% static 'css/feedback.css' %}" rel="stylesheet"/>
</head>
<body>
{% for i in fb %}
    {{ i.author }}<br>
    {{ i.text }}<br>
    {{ i.date }}<br>
    {{ i.rating }}<br>
{% endfor %}
<h4>Add new feedback</h4>
<form action="" method="POST">
    {% csrf_token %}
    <div>{{ feedback_form.as_p }}</div>
   <input type="submit" value="Add feedback">
</form><br>

</body>
</html>

blog/templates/blog/my_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My post</title>
</head>
<body>
<div style="text-align: center; margin-top: 40px; margin-bottom: 40px">
    <a style="font-size:35px; color: black" href="{% url 'post_list' %}">Teach Me Skills</a>
</div>
{% for post in items%}
<div style="margin-top: 20px;"> <a href="{% url 'post_detail' post_pk=post.pk %}">{{post.title}}</a><br>
    {{post.author}} {{post.publish_date}}<br>
    {{post.text}}<br>
</div>
{% endfor %}
</body>
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post detail</title>
</head>
<body>
<style>
    a {
     text-decoration: none;
    }
    a:hover {
<!--        font-size: 25px;-->
        color: yellow;
    }
</style>
<!--    {{ items }}-->
    <div style="text-align: center; margin-top: 40px; margin-bottom: 40px">
        <a style="font-size:35px; color: black" href="{% url 'post_list' %}">Teach Me Skills</a>
    </div>
  <div style="text-align: center; margin-top: 40px; margin-bottom: 40px; ">
        <a style="margin: 5px; font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'post_list' %}">
            Back to post
        </a>
        <a style="margin: 5px; font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'post_edit' post_pk=post.pk %}">
            Edit
        </a>
        {% if post.published == False %}
        <a style="margin: 5px; font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'published_post' post_pk=post.pk %}">
            Publicate
        </a>
        {% endif %}
        <a style="margin: 5px; font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'post_delete' post_pk=post.pk %}">
            Delete
        </a>
  </div>
         <div style="text-align: center; font-size: 25px; margin: 10px"> <em>{{ post.category }} </em></div>
     <div style="">
         <div style="text-align: center">
             <div style=""> <b>{{ post.author}}</b> <em>{{ post.publish_date}}</em></div>
           <div style="font-size: 30px; padding:20px">
              <a >{{ post.title }}</a>
            </div>
            <div style="text-align: left; margin: 20px; color: red">
                <p><em>Рейтинг: {{ counts }}</em></p>
            </div>
           <div style="margin-top: 30px">
                {{ post.text }}
           </div>
           <div style="margin: 40px 0px 0px 40px; text-align: left">
               <h4><em>Comments ({{ counter }})</em></h4>
           </div>
           <div style="margin: 30px 20px 20px 40px; pagging-text: 5px; text-align: left">
               {% for i in comments %}
               <b>{{ i.author}}</b> <em>{{ i.publish_date}}</em></br>
               {{ i.text }}</br></br>
               {% endfor %}
           </div>
           <div style="text-align: left; margin: 20px">
           <h4>Add new comment</h4>
           <form action="" method="POST">{% csrf_token %}
                {{comment_form.as_p}}
               <input type="submit" value="Add comment">
            </form><br>
            <button >
                <a style="color: black" href="{% url 'feedback' post_pk=post.pk %}">Feedbacks</a>
            </button>
            </div>

         </div>
     </div>

</body>
</html>

blog/templates/blog/post_edit.html
<!DOCTYPE html>
<html>
<body>

<h2>Edit Post</h2>

<form action="" method="POST">{% csrf_token %}
    <!--  <label for="fname">First name:</label><br>-->
    <!--    <input type="text" id="fname" name="fname" value="John"><br>-->
    <!--  <label for="lname">Last name:</label><br>-->
    <!--    <input type="text" id="lname" name="lname" value="Doe"><br><br>-->
    <!--  <input type="submit" value="Submit">-->
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post list</title>
</head>
<body>
<style>
    a {
     text-decoration: none;
    }
    a:hover {
<!--        font-size: 25px;-->
        color: yellow;
    }
</style>
<!--    {{ items }}-->
    <div style="text-align: center; margin-top: 40px; margin-bottom: 40px">
        <a style="font-size:35px; color: black" href="{% url 'post_list' %}">Teach Me Skills</a>
    </div>
    <div style="text-align: right; margin: 20px">
        {% if user.is_authenticated %}
        {% csrf_token %}
            <div><a href="{% url 'users:profile' %}">{{ user.username }}</a></div><br>
            <div><a href="{% url 'users:logout' %}">Logout</a></div>
        {% else %}
            <div><a href="{% url 'users:login' %}">Login</a></div><br>
        {% endif %}
    </div>
    <div style="margin: 20px; text-align: right">
        <h3>Category</h3>
        {% for i in category %}
        <a href="{% url 'categories' category_pk=i.pk %}">{{ i }}</a></br></br>
        {% endfor %}
    </div>
    <div style="margin-left: 50px ; margin-top: 40px; margin-bottom: 40px; ">
        <a style="font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'post_new' %}">
            Create new post
        </a>
        <a style="border: 2px solid; border-radius: 10px; padding: 5px"
           href="{% url 'my_posts' %}">
            My posts
        </a>
        <a style="margin: 10px; font-size:15px; color: black; border: 1px solid; border-radius: 20px; padding:10px"
           href="{% url 'post_draft' %}">
            Unpublished
        </a>
    </div>
    {% for post in items %}
     <div style="margin: 20px; display: inline-block">
         <div style="border: 1px solid; ">
            <div style="margin: 20px; text-align: center">
                <a href="{% url 'post_detail' post_pk=post.pk%}">{{ post.title }}</a>
            </div>
            <div style="border-top: 1px solid"> {{ post.author}}</div>
            <div style="border-top: 1px solid"> {{ post.publish_date}}</div>
         </div>
     </div>
     {% endfor %}</br>
     <h4>Number of posts: {{counter}}</h4>
     <div>
    <a  href="{% url 'recomends' %}">
        <p>Recomends</p>
    </a>
</div>
</body>
</html>

blog/templates/blog/post_new.html
<!DOCTYPE html>
<html>
<body>

<h2>New Post</h2>

<form action="" method="POST">{% csrf_token %}
    <!--  <label for="fname">First name:</label><br>-->
    <!--    <input type="text" id="fname" name="fname" value="John"><br>-->
    <!--  <label for="lname">Last name:</label><br>-->
    <!--    <input type="text" id="lname" name="lname" value="Doe"><br><br>-->
    <!--  <input type="submit" value="Submit">-->
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

</body>
</html>

blog/templates/blog/post_recomends.html
{% for i in spisok %}
        <div style="margin: 25px; margin-top:5px; display: inline-block">
            <div class="post_info">
                <div class="titles">
                    <a href="{% url 'post_detail' post_pk=i.pk %}">{{ i.title }} ({{ i.feedbacks__rating__avg }})</a>
<!--                    <a href="{% url 'post_detail' post_pk=i.pk %}">{{ i.feedbacks__rating__avg }}</a>-->
                </div>
              <div style="font-size: 16px; text-align: center; border-top: 1px solid">{{i.published_date}}</div>
            </div>
        </div>
{% endfor %}