blog/urls.py
from django.urls import path
from blog.views import *

urlpatterns = [
    path('', post_list, name='post_list'),
    path('post/draft', post_draft, name='post_draft'),
    path('post/category/<int:category_pk>', categories, name='categories'),
    path('post/detail/<int:post_pk>', post_detail, name='post_detail'),
    path('post/edit/<int:post_pk>', post_edit, name='post_edit'),
    path('post/published/<int:post_pk>', published_post, name='published_post'),
    path('post/delete/<int:post_pk>', post_delete, name='post_delete'),
    path('post/detail/comment_delete/<int:post_pk>/<int:comment_pk>', comment_delete,
         name='comment_delete'),
    path('post/new/', post_new, name='post_new'),
    path('post/detail/feedback/<int:post_pk>', feedback, name='feedback'),
    path('recommendations', recomends, name='recomends'),
    path('my_posts', my_posts, name='my_posts'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms

class UserLoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
         'placeholder': 'Введите имя пользователя'}))
     password = forms.CharField(widget=forms.PasswordInput(attrs={
         'placeholder': 'Введите пароль'}))

     class Meta:
        model = User
        fields = ('username', 'password')

     def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'

class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'image')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return redirect('post_list')
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return redirect('users:login')
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    return redirect('post_list')

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop - Авторизация</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.errors %}
                            <div class="alert
                                {% if messages %} alert-success {% else %} alert-warning {% endif %}
                                alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                {% if messages %}
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                {% else %}
                                    {{ form.non_field_errors }}
                                {% endif %}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username}}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password}}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>

users/templates/users/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop - Профиль</title>
   <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/profile.css' %}" rel="stylesheet"/>
</head>
<body class="bg-light">

<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-left">
                <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/users/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            {{ form.image }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'js/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop - Регистрация</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                {{ form.errors }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>